# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::223315263231:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::223315263231:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11KP8URPQ7678
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-22T22:02:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1475"
  uid: 1b69f489-7065-4fc2-a189-9accc106fd35
